### ISSUE TITLE
Issue in Chapter "Integrating QML and C++" example

### ISSUE THREAD

**Issue by malikfehan** [PacktPublishing/Qt5-C-GUI-Programming-Cookbook#1]
I am using QT 5.7. I could not run the example Chapter 5 "QML_Cpp". My application kept crashing. I found following code snippet was causing problem
File Name: main.cpp

```
QObject* messageText = root->findChild<QObject*>("messageText");
messageText->setProperty("text", QVariant("C++ is now in control!"));
messageText->setProperty("color", QVariant("green"));

QObject* square = root->findChild<QObject*>("square");
square->setProperty("color", QVariant("blue"));
```

I removed that line and called the setProperty function directly from the MainForm of file main.qml as following. 

 mouseArea.onClicked: {
           myclass.setMyObject(messageText);
}

**Comment by techsachinkumar** [comment]
Hi malikfehan

Could you tell me whether the previous code kept crashing for what error? 
Also you could provide us with a merge request with the following changes so that we can have a look.

Regards
